### ISSUE TITLE
Website Ideas 

### ISSUE THREAD

**Issue by burdoto** [comroid-git/comroid.org#1]
Idea 1:
Logo on top left and the red line completes as a HTML element to Form the bottom of the nav bar

**Comment by peanutbother** [comment]
you could create a picture of how you would like the layout to be, so we can use that as a first impression of your vision ;)

**Comment by peanutbother** [comment]
@auruwu which frameworks would you like to use?

**Comment by burdoto** [comment]
@peanutbother the HTML/js framework

**Comment by peanutbother** [comment]
Which is framework?
E.g. react

Which bundler? I recommend parcel.

**Comment by burdoto** [comment]
None. Plain HTML5, JS and CSS please.
If absolutely necessary, use a UI framework and schedule our own framework at times.

**Comment by peanutbother** [comment]
Why should we implement or own framework? This absolutely not necessary. We should already tested and we'll working frameworks if we decide to use such.

This discussion might be opinionated but we should consent to come up with an accessible, stable, performant and cross browser compatible site

**Comment by burdoto** [comment]
In the end, it's @auruwu's decision, although I would prefer plain language bases.

**Comment by burdoto** [comment]
Own framework would btw mean,
An active, server based solution that compiles the requested page from modular snippets which make up different parts of the web page.

**Comment by burdoto** [comment]
@peanutbother assigned for possible Webserver requests regarding dependencies.

**Comment by peanutbother** [comment]
Depending on the requirements I can provide one of my frameworks

**Comment by ch4wk0** [comment]
css
justify content: space between;

**Comment by burdoto** [comment]
I'm sorry, but how did you find this place, @ch4wk0?
