### ISSUE TITLE
create shortlink redirecting to discord widget url (#1)

### ISSUE THREAD

**Issue by peanutbother** [comroid-git/comroid.org#4]
##### belongs to #1 
to avoid having to update html on server / url change we could create a widget redirect url like we do for `invite.comroid.org`

https://github.com/comroid-git/comroid.org/blob/09a5832dc097ab8e08e06f677a25f29e76ce5d09/src/index.html#L53

I propose to use something like `discord-widget.comroid.org`

**Comment by burdoto** [comment]
Unfortunately, the Discord widget doesn't allow proxies.

**Comment by peanutbother** [comment]
no, not a proxy. we just set a 301 / 302 redirect, so the url in html doesn't change when it does on discord side. so we just change it at server level, and HTML stays the same.

**Comment by burdoto** [comment]
The thing is that the widget will barely ever change, this is such a niche case that we don't need a forward for this.
